# Builtin Laravel recipe.

[task.services]
run = """
bougie services add mariadb redis
bougie up mariadb redis
"""

[task.vendor]
creates = "vendor"
deps = ["composer.lock", "composer.json"]
run = "bougie run -- composer install"

[task.env]
creates = ".env"
deps = [".env.example"]
run = """
cp .env.example .env
bougie run -- php artisan key:generate
"""

[task.migrate]
deps = ["vendor", "services", "env"]
check = "bougie run -- php artisan migrate:status >/dev/null 2>&1"
run = "bougie run -- php artisan migrate --force"

[task.start]
deps = ["migrate"]
run = "bougie up server"
