//! Layer 1 conformance harness — runs the ported composer/semver
//! data-provider cases against bougie-semver's implementation.
//!
//! The fixture file (`tests/data/conformance.json`) is generated by
//! `scripts/port-composer-semver-tests.php` and committed. The test
//! is **`#[ignore]`d for now**: bougie-semver's Version / Constraint
//! implementations are stubs (Phase B of `bougie-composer-resolver`
//! per `RESOLVER_PLAN.md`). When the implementations land, drop the
//! `#[ignore]` and the test starts gating Layer 1 conformance per
//! `RESOLVER_TEST_PLAN.md`.
//!
//! Run manually with: `cargo test -p bougie-semver -- --ignored conformance`.

use bougie_semver::version::Version;
use serde::Deserialize;

const FIXTURE: &str = include_str!("data/conformance.json");

#[derive(Debug, Deserialize)]
struct Fixture {
    source: Source,
    suites: Vec<Suite>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct Source {
    repo: String,
    commit: String,
}

#[derive(Debug, Deserialize)]
struct Suite {
    class: String,
    method: String,
    cases: Vec<Vec<serde_json::Value>>,
}

/// Always-on smoke test: the committed fixture parses, and every suite
/// has a non-empty case list. Catches accidental regeneration with a
/// broken upstream checkout or a port-script bug.
#[test]
fn fixture_is_well_formed() {
    let fx: Fixture = serde_json::from_str(FIXTURE).expect("conformance.json is valid JSON");
    assert!(
        !fx.source.commit.is_empty(),
        "fixture must record upstream commit"
    );
    assert!(!fx.suites.is_empty(), "fixture must have suites");
    for s in &fx.suites {
        assert!(
            !s.cases.is_empty(),
            "suite {}::{} is empty — port script regression?",
            s.class,
            s.method
        );
    }
}

/// The full conformance run. Currently `#[ignore]`d because
/// `Version::parse` returns `ParseError::Unimplemented`. Each suite
/// dispatches by `method` name; new dispatches land as the underlying
/// impl grows. Suites with no dispatch yet are counted but skipped,
/// so this test never silently passes a suite that should be covered.
#[test]
#[ignore = "bougie-semver Version/Constraint impls are stubs; enable when Phase B lands"]
fn upstream_conformance() {
    let fx: Fixture = serde_json::from_str(FIXTURE).unwrap();

    let mut covered = 0usize;
    let mut skipped = 0usize;
    let mut failures: Vec<String> = vec![];

    for suite in &fx.suites {
        let dispatched = match suite.method.as_str() {
            "isValidVersions" => {
                for case in &suite.cases {
                    let input = case[0].as_str().unwrap();
                    let expected = case[1].as_bool().unwrap();
                    let actual = Version::parse(input).is_ok();
                    if actual != expected {
                        failures.push(format!(
                            "{}::{}: input={input:?} expected={expected} actual={actual}",
                            suite.class, suite.method
                        ));
                    }
                    covered += 1;
                }
                true
            }
            // Additional dispatches (compare, satisfies, normalize, …)
            // land as Version + Constraint grow. Until then they show
            // up in the skipped count, not silently absent.
            _ => false,
        };
        if !dispatched {
            skipped += suite.cases.len();
        }
    }

    if !failures.is_empty() {
        panic!(
            "{} conformance failures (covered {covered}, skipped {skipped}):\n  {}",
            failures.len(),
            failures.join("\n  ")
        );
    }
    eprintln!("conformance: covered={covered} skipped={skipped}");
}
