//! composer.json / composer.lock IO and editing primitives.
//!
//! Bougie touches both files when adding or removing an extension —
//! without invoking `composer require`, which would re-resolve the full
//! dependency graph and run platform checks against a PHP that hasn't
//! yet loaded the new ext. Doing the edits ourselves means we can:
//!
//! 1. Install the `.so` and enable it in `.bougie/conf.d/` *first*.
//! 2. Add the `require.ext-<name>` line to composer.json directly.
//! 3. Mirror it under `platform.ext-<name>` in composer.lock and
//!    recompute `content-hash`.
//!
//! Step 3 is what this module exists for. `composer install` accepts
//! the result without complaint; no `composer update` involved.
//!
//! See `Composer\Package\Locker::getContentHash` for the algorithm
//! (`src/Composer/Package/Locker.php:89` in composer/composer).

use crate::composer::php_json::{self, Mode};
use eyre::{eyre, Result};
use md5::{Digest, Md5};
use serde_json::{Map, Value};

/// Keys that participate in Composer's content-hash, in the order
/// PHP's `array_intersect($relevantKeys, array_keys($content))` would
/// produce. Order doesn't actually affect the hash (we `ksort` before
/// encoding) but mirroring composer's source is documentation.
const RELEVANT_KEYS: &[&str] = &[
    "name",
    "version",
    "require",
    "require-dev",
    "conflict",
    "replace",
    "provide",
    "minimum-stability",
    "prefer-stable",
    "repositories",
    "extra",
];

/// Compute Composer's `content-hash` for a composer.json byte stream.
///
/// Algorithm (verbatim from `Locker::getContentHash`):
///
/// 1. JSON-decode the composer.json bytes.
/// 2. Pick the [`RELEVANT_KEYS`] subset plus `config.platform` if
///    present. Nothing else under `config` participates.
/// 3. `ksort` the resulting top-level keys alphabetically.
/// 4. PHP `json_encode(..., 0)` — see [`php_json::Mode::Hash`].
/// 5. MD5 hex.
pub fn content_hash(composer_json_bytes: &[u8]) -> Result<String> {
    let parsed: Value = serde_json::from_slice(composer_json_bytes)
        .map_err(|e| eyre!("composer.json is not valid JSON: {e}"))?;
    let obj = parsed
        .as_object()
        .ok_or_else(|| eyre!("composer.json top level must be a JSON object"))?;

    let mut relevant: Map<String, Value> = Map::new();
    for key in RELEVANT_KEYS {
        if let Some(v) = obj.get(*key) {
            relevant.insert((*key).to_string(), v.clone());
        }
    }
    if let Some(platform) = obj
        .get("config")
        .and_then(Value::as_object)
        .and_then(|c| c.get("platform"))
    {
        let mut config_subset = Map::new();
        config_subset.insert("platform".to_string(), platform.clone());
        relevant.insert("config".to_string(), Value::Object(config_subset));
    }

    sort_top_level(&mut relevant);

    let bytes = php_json::encode(&Value::Object(relevant), Mode::Hash);
    let mut hasher = Md5::new();
    hasher.update(&bytes);
    Ok(hex_lower(&hasher.finalize()))
}

/// In-place ksort of an object's top-level keys (lexicographic on bytes,
/// matching PHP's default `ksort` for string keys). Nested objects keep
/// their own order — Composer's algorithm only sorts the top level.
fn sort_top_level(m: &mut Map<String, Value>) {
    let mut keys: Vec<String> = m.keys().cloned().collect();
    keys.sort();
    // serde_json::Map (with preserve_order) is backed by IndexMap, which
    // doesn't expose sort_keys without a feature; rebuild in order.
    let mut rebuilt: Map<String, Value> = Map::new();
    for k in keys {
        // unwrap: k came from m.keys() above.
        let v = m.shift_remove(&k).unwrap();
        rebuilt.insert(k, v);
    }
    *m = rebuilt;
}

fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[((b >> 4) & 0xf) as usize] as char);
        out.push(HEX[(b & 0xf) as usize] as char);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Fixture composer.json + its content-hash, both generated by
    /// running Composer's actual `Locker::getContentHash` algorithm
    /// against PHP 8.5.6. If this test ever drifts, the algorithm has
    /// changed upstream — re-run the oracle generator (see commit
    /// message for the one-liner).
    const FIXTURE_COMPOSER_JSON: &str = r#"{
    "name": "acme/widget-tool",
    "description": "An example application for testing.",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": "^8.3",
        "monolog/monolog": "^3.5",
        "ext-redis": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "^10.5"
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "config": {
        "sort-packages": true,
        "platform": {
            "php": "8.3.12"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-main": "1.0.x-dev"
        }
    },
    "authors": [
        {"name": "Alice", "email": "alice@example.com"}
    ]
}
"#;
    const FIXTURE_EXPECTED_HASH: &str = "9b37bf1b84c6c80e4dae34a4a6a8c18d";
    const FIXTURE_EXPECTED_ENCODED: &str = concat!(
        r#"{"config":{"platform":{"php":"8.3.12"}},"#,
        r#""extra":{"branch-alias":{"dev-main":"1.0.x-dev"}},"#,
        r#""minimum-stability":"stable","#,
        r#""name":"acme\/widget-tool","#,
        r#""prefer-stable":true,"#,
        r#""require":{"php":"^8.3","monolog\/monolog":"^3.5","ext-redis":"*"},"#,
        r#""require-dev":{"phpunit\/phpunit":"^10.5"}}"#,
    );

    #[test]
    fn fixture_hash_matches_real_php() {
        let actual = content_hash(FIXTURE_COMPOSER_JSON.as_bytes()).unwrap();
        assert_eq!(actual, FIXTURE_EXPECTED_HASH);
    }

    #[test]
    fn fixture_encoded_bytes_match_real_php() {
        // The hash is downstream of the encode; if this asserts succeeds
        // and the hash differs, the bug is in MD5 / hex (vanishingly
        // unlikely). If THIS fails, the encoder is wrong — surface
        // exactly which bytes diverged.
        let parsed: Value = serde_json::from_str(FIXTURE_COMPOSER_JSON).unwrap();
        let obj = parsed.as_object().unwrap();
        let mut relevant: Map<String, Value> = Map::new();
        for key in RELEVANT_KEYS {
            if let Some(v) = obj.get(*key) {
                relevant.insert((*key).to_string(), v.clone());
            }
        }
        if let Some(platform) = obj
            .get("config")
            .and_then(Value::as_object)
            .and_then(|c| c.get("platform"))
        {
            let mut config_subset = Map::new();
            config_subset.insert("platform".to_string(), platform.clone());
            relevant.insert("config".to_string(), Value::Object(config_subset));
        }
        sort_top_level(&mut relevant);
        let bytes = php_json::encode(&Value::Object(relevant), Mode::Hash);
        assert_eq!(String::from_utf8(bytes).unwrap(), FIXTURE_EXPECTED_ENCODED);
    }

    /// PHP-generated oracle for a composer.json containing non-ASCII
    /// BMP characters (`café/résumé`) — exercises the `\uXXXX`
    /// escape path under `Mode::Hash`.
    #[test]
    fn unicode_bmp_fixture_hash_matches_real_php() {
        let composer_json = serde_json::json!({
            "name": "café/résumé",
            "description": "Test 💩 with U+1F4A9",
            "require": {"php": "^8.3"},
        });
        let bytes = serde_json::to_vec(&composer_json).unwrap();
        // PHP-generated reference (composer.json above → flags=0 hash bytes)
        let expected = "4744162acf486d68ae8e72ecca67f4ab";
        assert_eq!(content_hash(&bytes).unwrap(), expected);
    }

    #[test]
    fn missing_relevant_keys_simply_omitted() {
        // A composer.json with none of the relevant keys hashes a `{}`.
        let bytes = br#"{"authors": [], "description": "x"}"#;
        let h = content_hash(bytes).unwrap();
        // md5("{}") confirms we don't accidentally pull in non-relevant
        // fields (`authors`, `description` etc. are not in RELEVANT_KEYS).
        assert_eq!(h, "99914b932bd37a50b983c5e7c90ae93b");
    }

    #[test]
    fn config_keys_other_than_platform_are_ignored() {
        // Only config.platform participates. config.sort-packages etc
        // must not affect the hash, otherwise editing local user prefs
        // would invalidate the lockfile.
        let base = br#"{"name":"a/b"}"#;
        let with_config = br#"{"name":"a/b","config":{"sort-packages":true,"optimize-autoloader":false}}"#;
        assert_eq!(
            content_hash(base).unwrap(),
            content_hash(with_config).unwrap()
        );
    }

    #[test]
    fn config_platform_participates() {
        let without = br#"{"name":"a/b"}"#;
        let with = br#"{"name":"a/b","config":{"platform":{"php":"8.3"}}}"#;
        assert_ne!(
            content_hash(without).unwrap(),
            content_hash(with).unwrap()
        );
    }

    #[test]
    fn rejects_non_object_top_level() {
        let err = content_hash(b"[]").unwrap_err();
        assert!(err.to_string().contains("must be a JSON object"));
    }

    #[test]
    fn rejects_invalid_json() {
        let err = content_hash(b"{not json").unwrap_err();
        assert!(err.to_string().contains("not valid JSON"));
    }

    #[test]
    fn hex_lower_is_lowercase() {
        assert_eq!(hex_lower(&[0xab, 0xcd]), "abcd");
        assert_eq!(hex_lower(&[0x00, 0xff]), "00ff");
    }
}
