<?php
declare(strict_types=1);

// Capture ground-truth `Composer\Semver\VersionParser::normalize()`
// outputs for each input in
// crates/bougie-autoloader/tests/data/version_normalize_inputs.txt.
// Re-run after bumping the pinned composer/semver version (currently
// shipped inside composer-2.8.12.phar). Output:
// crates/bougie-autoloader/tests/data/version_normalize.tsv with
// `input<TAB>output` lines (or `input<TAB>THROWS<TAB>message` when
// VersionParser refuses the input).

$pharPath = __DIR__ . '/../.cache/composer-2.8.12.phar';
if (!is_file($pharPath)) {
    fwrite(STDERR, "missing composer phar at {$pharPath}\n");
    exit(1);
}
require 'phar://' . $pharPath . '/vendor/autoload.php';

use Composer\Semver\VersionParser;

$inputsPath = __DIR__ . '/../crates/bougie-autoloader/tests/data/version_normalize_inputs.txt';
$outputPath = __DIR__ . '/../crates/bougie-autoloader/tests/data/version_normalize.tsv';

$lines = file($inputsPath, FILE_IGNORE_NEW_LINES);
if ($lines === false) {
    fwrite(STDERR, "could not read {$inputsPath}\n");
    exit(1);
}

$parser = new VersionParser();
$out = "# generated by scripts/gen-version-normalize-fixtures.php — do not hand-edit\n";
$out .= "# Lines are tab-separated: input<TAB>output OR input<TAB>THROWS<TAB>message.\n";
$out .= "# The input column preserves the original line, including any\n";
$out .= "# leading whitespace, so the harness can replay it verbatim.\n";

foreach ($lines as $line) {
    // Skip pure comments / blank visual separators. We DO keep the
    // leading-whitespace test case (the input file's "  1.0.0" line
    // exercises trim()): tell it apart from comments by checking trim
    // before the `#` check.
    $trimmed = ltrim($line);
    if ($trimmed === '' || str_starts_with($trimmed, '#')) {
        continue;
    }

    try {
        $normalized = $parser->normalize($line);
        $out .= $line . "\t" . $normalized . "\n";
    } catch (\Throwable $e) {
        // Replace newlines/tabs in the exception message so the TSV
        // stays parseable.
        $msg = strtr($e->getMessage(), ["\t" => ' ', "\n" => ' ']);
        $out .= $line . "\tTHROWS\t" . $msg . "\n";
    }
}

if (file_put_contents($outputPath, $out) === false) {
    fwrite(STDERR, "could not write {$outputPath}\n");
    exit(1);
}
fwrite(STDERR, "wrote {$outputPath}\n");
