#!/usr/bin/env bash
# Generate per-fixture autoload expecteds by running Composer's own
# dump-autoload against minimal composer.json inputs.
#
# Re-run when:
#   - The pinned Composer version (REFERENCE_COMPOSER_VERSION in
#     crates/bougie-autoloader/src/lib.rs) bumps.
#   - You add a new fixture under crates/bougie-autoloader/tests/fixtures/.
#
# Each fixture dir holds:
#   input/      — committed source of truth (composer.json + PHP files
#                 for any path-referenced packages).
#   expected/   — generated output from this script. Overwritten on
#                 every run; do NOT hand-edit.
#
# Usage: scripts/generate-autoload-fixtures.sh /path/to/composer.phar
#        (defaults to /tmp/composer-2.8.phar if no arg given).
#
# The script's job is fixtures, not implementation; the actual bougie
# autoloader implementation lives in crates/bougie-autoloader.

set -euo pipefail

COMPOSER_PHAR="${1:-/tmp/composer-2.8.phar}"
if [[ ! -f "$COMPOSER_PHAR" ]]; then
    echo "missing composer phar at $COMPOSER_PHAR" >&2
    echo "fetch with: curl -sLo /tmp/composer-2.8.phar https://getcomposer.org/download/2.8.12/composer.phar" >&2
    exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIXTURES_DIR="$REPO_ROOT/crates/bougie-autoloader/tests/fixtures"

# Files generated by Composer that we DO NOT diff: these are bundled
# verbatim from Composer's own source (ClassLoader.php, InstalledVersions.php,
# LICENSE, platform_check.php). Byte-equivalence to *those* would just
# be reading Composer's source back to itself; we only diff the genuinely-
# generated files (autoload_*.php, installed.json, installed.php).
# `autoload.php` lives at vendor/autoload.php; everything else is
# under vendor/composer/. The harness mirrors this layout.
GENERATED_TOPLEVEL=(
    autoload.php
)
GENERATED_COMPOSER_DIR=(
    autoload_namespaces.php
    autoload_psr4.php
    autoload_classmap.php
    autoload_files.php
    autoload_real.php
    autoload_static.php
    installed.json
    installed.php
)

run_fixture() {
    local name="$1"
    local input="$FIXTURES_DIR/$name/input"
    local expected="$FIXTURES_DIR/$name/expected"

    if [[ ! -d "$input" ]]; then
        echo "skip $name: no input/ dir" >&2
        return
    fi

    # Run dump in a tempdir copy so we don't pollute the committed input.
    local work
    work="$(mktemp -d)"
    trap "rm -rf '$work'" RETURN
    cp -R "$input"/. "$work/"

    (
        cd "$work"
        php "$COMPOSER_PHAR" install --no-progress --no-interaction --quiet
    )

    rm -rf "$expected"
    mkdir -p "$expected/vendor/composer"
    for f in "${GENERATED_TOPLEVEL[@]}"; do
        src="$work/vendor/$f"
        [[ -f "$src" ]] && cp "$src" "$expected/vendor/$f"
    done
    for f in "${GENERATED_COMPOSER_DIR[@]}"; do
        src="$work/vendor/composer/$f"
        [[ -f "$src" ]] && cp "$src" "$expected/vendor/composer/$f"
    done

    echo "generated $name" >&2
}

# Iterate every fixture directory.
for dir in "$FIXTURES_DIR"/*/; do
    [[ -d "$dir" ]] || continue
    name="$(basename "$dir")"
    run_fixture "$name"
done

echo "done. fixtures committed at $FIXTURES_DIR" >&2
