//! Byte-equivalence harness — for each fixture under
//! `tests/fixtures/<name>/{input,expected}/`, runs bougie's
//! `dump_autoload` against the input and asserts every file it writes
//! matches the committed expected output byte-for-byte.
//!
//! Expected outputs are generated by
//! `scripts/generate-autoload-fixtures.sh` against the pinned
//! Composer version (see `REFERENCE_COMPOSER_VERSION` in lib.rs).
//! Re-run that script + commit when bumping the pin.
//!
//! Currently `#[ignore]`d because `dump_autoload` returns
//! `DumpError::Unimplemented`. Phase 1 of `AUTOLOADER_PLAN.md` lights
//! it up. The well-formedness smoke test below stays always-on so we
//! catch fixture corruption independently of the implementation.

use bougie_autoloader::{dump_autoload, DumpRequest};
use std::path::{Path, PathBuf};

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

/// Always-on: every fixture dir has `input/composer.json` and a
/// non-empty `expected/` tree. Fast (~milliseconds) — catches a broken
/// fixture-gen run or a hand-edit before the rest of the suite would.
#[test]
fn fixtures_are_well_formed() {
    let dirs = fixture_dirs();
    assert!(!dirs.is_empty(), "no fixtures under {FIXTURES_DIR}");
    for dir in &dirs {
        let name = dir.file_name().unwrap().to_string_lossy();
        let input_json = dir.join("input").join("composer.json");
        assert!(
            input_json.is_file(),
            "fixture {name}: missing input/composer.json"
        );
        let expected = dir.join("expected");
        assert!(expected.is_dir(), "fixture {name}: missing expected/ dir");
        let count = walk(&expected).count();
        assert!(
            count > 0,
            "fixture {name}: expected/ is empty — did generate-autoload-fixtures.sh run?"
        );
    }
}

#[test]
#[ignore = "bougie-autoloader::dump_autoload is a stub; enable when AUTOLOADER_PLAN Phase 1 lands"]
fn byte_equivalence_against_composer() {
    let mut failures: Vec<String> = vec![];

    for dir in fixture_dirs() {
        let name = dir.file_name().unwrap().to_string_lossy().into_owned();
        let work = match copy_input_to_tempdir(&dir) {
            Ok(p) => p,
            Err(e) => {
                failures.push(format!("{name}: setup failed: {e}"));
                continue;
            }
        };

        let req = DumpRequest {
            project_root: work.path(),
            optimize: false,
            classmap_authoritative: false,
            no_dev: false,
        };
        if let Err(e) = dump_autoload(&req) {
            failures.push(format!("{name}: dump_autoload failed: {e}"));
            continue;
        }

        let expected_root = dir.join("expected");
        for rel in walk(&expected_root) {
            let expected_path = expected_root.join(&rel);
            let actual_path = work.path().join(&rel);
            let expected_bytes = match std::fs::read(&expected_path) {
                Ok(b) => b,
                Err(e) => {
                    failures.push(format!("{name}: read {}: {e}", rel.display()));
                    continue;
                }
            };
            let actual_bytes = match std::fs::read(&actual_path) {
                Ok(b) => b,
                Err(e) => {
                    failures.push(format!(
                        "{name}: bougie did not produce {}: {e}",
                        rel.display()
                    ));
                    continue;
                }
            };
            if expected_bytes != actual_bytes {
                failures.push(format!(
                    "{name}: {} differs ({} expected bytes vs {} actual)",
                    rel.display(),
                    expected_bytes.len(),
                    actual_bytes.len(),
                ));
            }
        }
    }

    if !failures.is_empty() {
        panic!(
            "{} byte-equivalence failures:\n  {}",
            failures.len(),
            failures.join("\n  ")
        );
    }
}

fn fixture_dirs() -> Vec<PathBuf> {
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(FIXTURES_DIR)
        .expect("read fixtures dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();
    dirs
}

fn walk(root: &Path) -> impl Iterator<Item = PathBuf> {
    let mut out = vec![];
    walk_into(root, root, &mut out);
    out.sort();
    out.into_iter()
}

fn walk_into(root: &Path, dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let p = entry.path();
        if p.is_dir() {
            walk_into(root, &p, out);
        } else if p.is_file() {
            if let Ok(rel) = p.strip_prefix(root) {
                out.push(rel.to_path_buf());
            }
        }
    }
}

fn copy_input_to_tempdir(fixture_dir: &Path) -> std::io::Result<TempDir> {
    let td = TempDir::new()?;
    copy_dir(&fixture_dir.join("input"), td.path())?;
    Ok(td)
}

fn copy_dir(src: &Path, dst: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

/// Minimal tempdir helper (no `tempfile` dep — bougie-autoloader has
/// no production dependencies yet, and we want to keep dev-deps lean
/// per the conventions surveyed in the test-suite plan).
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new() -> std::io::Result<Self> {
        let base = std::env::temp_dir();
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = base.join(format!("bougie-autoloader-fx-{nanos}-{}", std::process::id()));
        std::fs::create_dir(&path)?;
        Ok(Self { path })
    }
    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}
