//! Per-project `.bougie/conf.d/` fragment generation for user-installed
//! extensions. Bundled extensions are handled separately by
//! `commands::sync::replicate_install_conf_d`, which copies the
//! `00-XX-<name>.ini` shipped with each PHP install. This module
//! covers the `20-<name>.ini` fragments that *enable* extensions
//! bougie installed itself (i.e. via `bougie ext add`).
//!
//! The filename uses a `20-` prefix so PHP's alphabetic conf.d scan
//! loads them after the `00-XX-*.ini` bundled fragments — at which
//! point opcache and friends are already up — but before any user
//! `50-*.ini` overrides (CLI.md §6.2).

use crate::index::wire::LoadDirective;
use eyre::{eyre, Result, WrapErr};
use std::io::Write;
use std::path::{Path, PathBuf};

/// Write — atomically — a single `20-<name>.ini` fragment that loads
/// the given `.so` via the right INI directive. Returns the fragment's
/// absolute path so callers can surface it in `--format json` output.
///
/// Existing fragments are overwritten unconditionally: a re-install at
/// a new version updates the `.so` path in place.
pub fn write_ext_fragment(
    project_root: &Path,
    name: &str,
    so_path: &Path,
    load: LoadDirective,
) -> Result<PathBuf> {
    let dir = project_root.join(".bougie").join("conf.d");
    std::fs::create_dir_all(&dir)
        .wrap_err_with(|| format!("creating {}", dir.display()))?;
    let path = dir.join(format!("20-{name}.ini"));
    let body = format!(
        "; managed by bougie — do not edit; regenerated by `bougie ext add {name}`\n\
         {directive}={so}\n",
        directive = load.ini_directive(),
        so = so_path.display(),
    );
    write_atomic(&path, body.as_bytes())?;
    Ok(path)
}

/// Remove a `20-<name>.ini` fragment if it exists. Returns `Ok(true)`
/// when a file was removed, `Ok(false)` if no fragment was present.
pub fn remove_ext_fragment(project_root: &Path, name: &str) -> Result<bool> {
    let path = project_root
        .join(".bougie")
        .join("conf.d")
        .join(format!("20-{name}.ini"));
    match std::fs::remove_file(&path) {
        Ok(()) => Ok(true),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(eyre!("removing {}: {e}", path.display())),
    }
}

/// tempfile + rename in the same directory. Same atomicity guarantees
/// as `composer::lockfile::write_json_bytes` (POSIX same-fs rename).
fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    let dir = path.parent().ok_or_else(|| {
        eyre!("path {} has no parent directory", path.display())
    })?;
    let mut tf = tempfile::NamedTempFile::new_in(dir)
        .wrap_err_with(|| format!("creating tempfile in {}", dir.display()))?;
    tf.as_file_mut()
        .write_all(bytes)
        .wrap_err_with(|| format!("writing {}", tf.path().display()))?;
    tf.as_file_mut()
        .sync_all()
        .wrap_err_with(|| format!("fsyncing {}", tf.path().display()))?;
    tf.persist(path)
        .map_err(|e| eyre!("renaming temp to {}: {e}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn writes_regular_extension_fragment() {
        let td = TempDir::new().unwrap();
        let so = td.path().join("store/redis-6/redis.so");
        let path = write_ext_fragment(
            td.path(),
            "redis",
            &so,
            LoadDirective::Extension,
        )
        .unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(path.ends_with(".bougie/conf.d/20-redis.ini"));
        assert!(body.starts_with("; managed by bougie"));
        assert!(body.contains(&format!("extension={}", so.display())));
        assert!(!body.contains("zend_extension"));
    }

    #[test]
    fn writes_zend_extension_fragment() {
        let td = TempDir::new().unwrap();
        let so = td.path().join("store/xdebug-3/xdebug.so");
        let path = write_ext_fragment(
            td.path(),
            "xdebug",
            &so,
            LoadDirective::ZendExtension,
        )
        .unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains(&format!("zend_extension={}", so.display())));
    }

    #[test]
    fn overwrites_existing_fragment() {
        // A re-install at a new path must replace the old fragment so
        // PHP loads the right `.so` after `bougie sync`.
        let td = TempDir::new().unwrap();
        let old_so = td.path().join("store/redis-5/redis.so");
        let new_so = td.path().join("store/redis-6/redis.so");
        write_ext_fragment(td.path(), "redis", &old_so, LoadDirective::Extension).unwrap();
        let path =
            write_ext_fragment(td.path(), "redis", &new_so, LoadDirective::Extension).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains(&format!("extension={}", new_so.display())));
        assert!(!body.contains(&format!("extension={}", old_so.display())));
    }

    #[test]
    fn remove_reports_state() {
        let td = TempDir::new().unwrap();
        let so = td.path().join("store/redis-6/redis.so");
        write_ext_fragment(td.path(), "redis", &so, LoadDirective::Extension).unwrap();
        assert!(remove_ext_fragment(td.path(), "redis").unwrap());
        assert!(!remove_ext_fragment(td.path(), "redis").unwrap());
    }

    #[test]
    fn remove_of_absent_is_noop() {
        let td = TempDir::new().unwrap();
        assert!(!remove_ext_fragment(td.path(), "ghost").unwrap());
    }
}
