//! Per-project `.bougie/conf.d/` fragment generation for user-installed
//! extensions. Bundled extensions are handled separately by
//! `commands::sync::replicate_install_conf_d`, which copies the
//! `00-XX-<name>.ini` shipped with each PHP install. This module
//! covers the `<NN>-<name>.ini` fragments that *enable* extensions
//! bougie installed itself (i.e. via `bougie ext add` or sync's
//! composer.json auto-install).
//!
//! The numeric prefix `<NN>` is chosen by `install::conf_d_prefix_for`
//! to mirror `php-build-standalone`'s build-time numbering: `35-` for
//! `pdo_*` (after `30-pdo`), `40-` for `mysqli/sqlite3/pgsql`, `20-`
//! otherwise. This keeps PHP's alphabetic conf.d scan loading
//! dependents after dependencies — `20-pdo_mysql.ini` ahead of
//! `30-pdo.ini` would trigger `undefined symbol: pdo_dbh_ce`.

use crate::index::wire::LoadDirective;
use crate::install::conf_d_prefix_for;
use eyre::{eyre, Result, WrapErr};
use std::io::Write;
use std::path::{Path, PathBuf};

/// Write — atomically — a single `<NN>-<name>.ini` fragment that loads
/// the given `.so` via the right INI directive. Returns the fragment's
/// absolute path so callers can surface it in `--format json` output.
/// `<NN>` is determined by [`conf_d_prefix_for`] — see module docs.
///
/// Existing fragments are overwritten unconditionally: a re-install at
/// a new version updates the `.so` path in place.
pub fn write_ext_fragment(
    project_root: &Path,
    name: &str,
    so_path: &Path,
    load: LoadDirective,
) -> Result<PathBuf> {
    let dir = project_root.join(".bougie").join("conf.d");
    std::fs::create_dir_all(&dir)
        .wrap_err_with(|| format!("creating {}", dir.display()))?;
    let prefix = conf_d_prefix_for(name);
    let path = dir.join(format!("{prefix}-{name}.ini"));
    // Drop any stale fragment for this ext at a different prefix —
    // happens when bougie's prefix mapping changes between releases
    // (e.g. `20-pdo_mysql.ini` from an older bougie has to go before
    // we write `35-pdo_mysql.ini` or PHP would load pdo_mysql before
    // pdo.so initializes pdo_dbh_ce).
    remove_other_prefix_fragments(&dir, name, prefix)?;
    let body = format!(
        "; managed by bougie — do not edit; regenerated by `bougie ext add {name}`\n\
         {directive}={so}\n",
        directive = load.ini_directive(),
        so = so_path.display(),
    );
    write_atomic(&path, body.as_bytes())?;
    Ok(path)
}

/// Remove any `<NN>-<name>.ini` fragment if it exists. Returns
/// `Ok(true)` when a file was removed, `Ok(false)` if no fragment was
/// present. Scans all numeric prefixes rather than only the canonical
/// one so that `bougie ext remove` works after a prefix mapping change.
pub fn remove_ext_fragment(project_root: &Path, name: &str) -> Result<bool> {
    let dir = project_root.join(".bougie").join("conf.d");
    let entries = match std::fs::read_dir(&dir) {
        Ok(e) => e,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(e) => return Err(eyre!("reading {}: {e}", dir.display())),
    };
    let target_suffix = format!("-{name}.ini");
    let mut removed = false;
    for entry in entries.flatten() {
        let fname = entry.file_name();
        let Some(fname_str) = fname.to_str() else { continue };
        if fname_str.ends_with(&target_suffix) && has_numeric_prefix(fname_str) {
            match std::fs::remove_file(entry.path()) {
                Ok(()) => removed = true,
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(e) => return Err(eyre!("removing {}: {e}", entry.path().display())),
            }
        }
    }
    Ok(removed)
}

/// Delete `<other_prefix>-<name>.ini` fragments where `other_prefix`
/// is any numeric prefix that doesn't match `keep_prefix`. Used by
/// [`write_ext_fragment`] to keep exactly one fragment per ext when
/// the canonical prefix changes between bougie releases.
fn remove_other_prefix_fragments(dir: &Path, name: &str, keep_prefix: u32) -> Result<()> {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(eyre!("reading {}: {e}", dir.display())),
    };
    let target_suffix = format!("-{name}.ini");
    let keep_full = format!("{keep_prefix}-{name}.ini");
    for entry in entries.flatten() {
        let fname = entry.file_name();
        let Some(fname_str) = fname.to_str() else { continue };
        if fname_str == keep_full {
            continue;
        }
        if fname_str.ends_with(&target_suffix) && has_numeric_prefix(fname_str) {
            let _ = std::fs::remove_file(entry.path());
        }
    }
    Ok(())
}

fn has_numeric_prefix(filename: &str) -> bool {
    let Some(dash) = filename.find('-') else { return false };
    let prefix = &filename[..dash];
    !prefix.is_empty() && prefix.chars().all(|c| c.is_ascii_digit())
}

/// tempfile + rename in the same directory. Same atomicity guarantees
/// as `composer::lockfile::write_json_bytes` (POSIX same-fs rename).
fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    let dir = path.parent().ok_or_else(|| {
        eyre!("path {} has no parent directory", path.display())
    })?;
    let mut tf = tempfile::NamedTempFile::new_in(dir)
        .wrap_err_with(|| format!("creating tempfile in {}", dir.display()))?;
    tf.as_file_mut()
        .write_all(bytes)
        .wrap_err_with(|| format!("writing {}", tf.path().display()))?;
    tf.as_file_mut()
        .sync_all()
        .wrap_err_with(|| format!("fsyncing {}", tf.path().display()))?;
    tf.persist(path)
        .map_err(|e| eyre!("renaming temp to {}: {e}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn writes_regular_extension_fragment() {
        let td = TempDir::new().unwrap();
        let so = td.path().join("store/redis-6/redis.so");
        let path = write_ext_fragment(
            td.path(),
            "redis",
            &so,
            LoadDirective::Extension,
        )
        .unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(path.ends_with(".bougie/conf.d/20-redis.ini"));
        assert!(body.starts_with("; managed by bougie"));
        assert!(body.contains(&format!("extension={}", so.display())));
        assert!(!body.contains("zend_extension"));
    }

    #[test]
    fn writes_zend_extension_fragment() {
        let td = TempDir::new().unwrap();
        let so = td.path().join("store/xdebug-3/xdebug.so");
        let path = write_ext_fragment(
            td.path(),
            "xdebug",
            &so,
            LoadDirective::ZendExtension,
        )
        .unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains(&format!("zend_extension={}", so.display())));
    }

    #[test]
    fn overwrites_existing_fragment() {
        // A re-install at a new path must replace the old fragment so
        // PHP loads the right `.so` after `bougie sync`.
        let td = TempDir::new().unwrap();
        let old_so = td.path().join("store/redis-5/redis.so");
        let new_so = td.path().join("store/redis-6/redis.so");
        write_ext_fragment(td.path(), "redis", &old_so, LoadDirective::Extension).unwrap();
        let path =
            write_ext_fragment(td.path(), "redis", &new_so, LoadDirective::Extension).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains(&format!("extension={}", new_so.display())));
        assert!(!body.contains(&format!("extension={}", old_so.display())));
    }

    #[test]
    fn remove_reports_state() {
        let td = TempDir::new().unwrap();
        let so = td.path().join("store/redis-6/redis.so");
        write_ext_fragment(td.path(), "redis", &so, LoadDirective::Extension).unwrap();
        assert!(remove_ext_fragment(td.path(), "redis").unwrap());
        assert!(!remove_ext_fragment(td.path(), "redis").unwrap());
    }

    #[test]
    fn remove_of_absent_is_noop() {
        let td = TempDir::new().unwrap();
        assert!(!remove_ext_fragment(td.path(), "ghost").unwrap());
    }

    #[test]
    fn pdo_drivers_use_35_prefix() {
        // pdo_* must load after `30-pdo.ini` or PHP errors with
        // "undefined symbol: pdo_dbh_ce". The 35- prefix mirrors
        // php-build-standalone's build-php.sh numbering.
        let td = TempDir::new().unwrap();
        let so = td.path().join("store/ext/pdo_mysql.so");
        let path = write_ext_fragment(
            td.path(),
            "pdo_mysql",
            &so,
            LoadDirective::Extension,
        )
        .unwrap();
        assert!(path.ends_with(".bougie/conf.d/35-pdo_mysql.ini"));
    }

    #[test]
    fn db_drivers_use_40_prefix() {
        // mysqli / sqlite3 / pgsql load alongside `35-pdo_*` but after
        // them; matches build-php.sh convention.
        let td = TempDir::new().unwrap();
        for name in ["mysqli", "sqlite3", "pgsql"] {
            let so = td.path().join(format!("store/ext/{name}.so"));
            let path = write_ext_fragment(
                td.path(),
                name,
                &so,
                LoadDirective::Extension,
            )
            .unwrap();
            assert!(
                path.ends_with(format!(".bougie/conf.d/40-{name}.ini")),
                "{}: expected 40- prefix, got {}",
                name,
                path.display()
            );
        }
    }

    #[test]
    fn rewrite_at_new_prefix_drops_old_fragment() {
        // Simulate the upgrade case: a previous bougie wrote
        // `20-pdo_mysql.ini`; after the prefix mapping change we
        // should end up with just `35-pdo_mysql.ini`.
        let td = TempDir::new().unwrap();
        let dir = td.path().join(".bougie/conf.d");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("20-pdo_mysql.ini"), "extension=old\n").unwrap();
        let so = td.path().join("store/ext/pdo_mysql.so");
        write_ext_fragment(td.path(), "pdo_mysql", &so, LoadDirective::Extension)
            .unwrap();
        assert!(dir.join("35-pdo_mysql.ini").exists());
        assert!(!dir.join("20-pdo_mysql.ini").exists());
    }

    #[test]
    fn remove_finds_fragment_at_any_numeric_prefix() {
        let td = TempDir::new().unwrap();
        let dir = td.path().join(".bougie/conf.d");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("35-pdo_mysql.ini"), "extension=x\n").unwrap();
        assert!(remove_ext_fragment(td.path(), "pdo_mysql").unwrap());
        assert!(!dir.join("35-pdo_mysql.ini").exists());
    }
}
