//! Port of Composer's `AutoloadGenerator::getAutoloadRealFile`.
//!
//! Emits `vendor/composer/autoload_real.php` — the runtime entry
//! point referenced by `vendor/autoload.php`. Constructed by
//! concatenating fixed heredoc blocks with conditional inserts for
//! `--classmap-authoritative`, files-autoload, platform-check, etc.
//!
//! Composer's heredoc semantics: the newline immediately preceding
//! the closing identifier is dropped. We mirror that by sizing each
//! block's trailing newlines accordingly — gets us byte-equivalence
//! without needing to actually run a PHP heredoc.

use std::fmt::Write;

/// `has_files`: at least one package or root declares an `autoload.files`
/// entry — adds the per-file include loop.
///
/// `classmap_authoritative`: emits `$loader->setClassMapAuthoritative(true);`
/// before `$loader->register(...)`.
pub(crate) fn emit(content_hash: &str, has_files: bool, classmap_authoritative: bool) -> String {
    let mut out = String::with_capacity(2048);

    // HEADER block — same for every fixture. Ends with `}\n\n` (one
    // blank line after the `if (null !== self::$loader)` close brace,
    // per Composer's heredoc dropping the newline that precedes the
    // closing `HEADER;` identifier).
    out.push_str("<?php\n\n");
    out.push_str("// autoload_real.php @generated by Composer\n\n");
    let _ = writeln!(out, "class ComposerAutoloaderInit{content_hash}");
    out.push_str("{\n");
    out.push_str("    private static $loader;\n\n");
    out.push_str("    public static function loadClassLoader($class)\n");
    out.push_str("    {\n");
    out.push_str("        if ('Composer\\Autoload\\ClassLoader' === $class) {\n");
    out.push_str("            require __DIR__ . '/ClassLoader.php';\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    /**\n");
    out.push_str("     * @return \\Composer\\Autoload\\ClassLoader\n");
    out.push_str("     */\n");
    out.push_str("    public static function getLoader()\n");
    out.push_str("    {\n");
    out.push_str("        if (null !== self::$loader) {\n");
    out.push_str("            return self::$loader;\n");
    out.push_str("        }\n\n");

    // platform_check.php require — only when composer.json's
    // `config.platform-check` is on. Our DumpRequest doesn't surface
    // it yet; left for a follow-up.

    // CLASSLOADER_INIT — register the bootstrap loader, instantiate
    // ClassLoader, unregister the bootstrap.
    let _ = writeln!(
        out,
        "        spl_autoload_register(array('ComposerAutoloaderInit{content_hash}', 'loadClassLoader'), true, true);"
    );
    out.push_str(
        "        self::$loader = $loader = new \\Composer\\Autoload\\ClassLoader(\\dirname(__DIR__));\n",
    );
    let _ = writeln!(
        out,
        "        spl_autoload_unregister(array('ComposerAutoloaderInit{content_hash}', 'loadClassLoader'));"
    );
    out.push('\n');

    // STATIC_INIT — require autoload_static.php + invoke its
    // getInitializer.
    out.push_str("        require __DIR__ . '/autoload_static.php';\n");
    let _ = writeln!(
        out,
        "        call_user_func(\\Composer\\Autoload\\ComposerStaticInit{content_hash}::getInitializer($loader));"
    );
    out.push('\n');

    // CLASSMAPAUTHORITATIVE — emits between static-init and the
    // loader register call. No trailing blank line in Composer's
    // template.
    if classmap_authoritative {
        out.push_str("        $loader->setClassMapAuthoritative(true);\n");
    }

    // REGISTER_LOADER — always present.
    out.push_str("        $loader->register(true);\n\n");

    // INCLUDE_FILES — per-file loader loop, only when any package or
    // root declared autoload.files.
    if has_files {
        let _ = writeln!(
            out,
            "        $filesToLoad = \\Composer\\Autoload\\ComposerStaticInit{content_hash}::$files;"
        );
        out.push_str("        $requireFile = \\Closure::bind(static function ($fileIdentifier, $file) {\n");
        out.push_str(
            "            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {\n",
        );
        out.push_str(
            "                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;\n\n",
        );
        out.push_str("                require $file;\n");
        out.push_str("            }\n");
        out.push_str("        }, null, null);\n");
        out.push_str("        foreach ($filesToLoad as $fileIdentifier => $file) {\n");
        out.push_str("            $requireFile($fileIdentifier, $file);\n");
        out.push_str("        }\n\n");
    }

    // METHOD_FOOTER + FOOTER (always).
    out.push_str("        return $loader;\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn minimal_shape() {
        let s = emit("deadbeef", false, false);
        assert!(s.starts_with("<?php\n\n// autoload_real.php"));
        assert!(s.contains("class ComposerAutoloaderInitdeadbeef\n"));
        assert!(s.ends_with("}\n"));
        // No files loop, no classmap-authoritative line
        assert!(!s.contains("setClassMapAuthoritative"));
        assert!(!s.contains("filesToLoad"));
    }

    #[test]
    fn classmap_authoritative_inserts_before_register() {
        let s = emit("deadbeef", false, true);
        let auth_pos = s.find("setClassMapAuthoritative").unwrap();
        let register_pos = s.find("$loader->register(true)").unwrap();
        assert!(auth_pos < register_pos);
    }

    #[test]
    fn files_block_present_when_requested() {
        let s = emit("deadbeef", true, false);
        assert!(s.contains("$filesToLoad"));
        assert!(s.contains("$requireFile"));
    }
}
